import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const sendGraph = async(event) => {
    const interval = event.target.interval.value;
    const endRange = event.target.endRange.value;
    const email = event.target.email.value;

    const body = new FormData();

    body.append("endRange", endRange);
    body.append("interval", interval);
    body.append("email", email);

    await fetch(`https://usercd38747477a7ff2.app.vtxhub.com/get_plot`, {
      method: "POST",
      body
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Enter Stuff Here</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={sendGraph}>
          Interval: <input type="text" id="Interval"></input>
          End range: <input type="text" id="endRange"></input>
          Email: <input type="text" id="email"></input>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
