import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

function sleep(delay) {
  var start = new Date().getTime();
  while (new Date().getTime() < start + delay);
}

export default function Home() {
  const sendGraph = async(event) => {
    event.preventDefault();
    const interval = document.getElementById("Interval").value;
    const endRange = document.getElementById("endRange").value
    const email = document.getElementById("email").value;

    console.log(interval)

    const body = new FormData();

    body.append("endRange", parseFloat(endRange));
    body.append("interval", parseFloat(interval));
    body.append("email", email);

    fetch(`https://usercd38747477a7ff2.app.vtxhub.com/get_plot`, {
      method: "POST",
      body
    })

    // window.location.reload()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Enter Stuff Here</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={sendGraph}>
          Interval: <input type="text" id="Interval"></input>
          <p></p>
          End range: <input type="text" id="endRange"></input>
          <p></p>
          Email: <input type="text" id="email"></input>
          <p></p>
          <button type="submit">Submit</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
